### PR TITLE
Refactor test llvmreadobj stackmap parser

### PR DESCRIPTION
**Pull request by jacob-hughes**
This preliminary PR does some refactor work so that upcoming changes will be easier to review.

The main change here is that we split the parsing of each main stackmap 'block' into distinct functions: a function parser, and a record parser. This makes including functionality to parse additional parts of the llvm-readobj stackmap much easier.

### CODE REVIEW

**Comment by jacob-hughes** [comment]
Sorry @vext01 I know you've already looked at this one. But I've created a new PR because it's now rebased from a working CI integration

**Comment by vext01** [comment]
This is the same change as before, i.e. already reviewed?

**Comment by jacob-hughes** [comment]
Yes

**Pull request merged**
